name: websocket
description: Universal package for websocket, compatible with web, flutter, and vm.
version: 1.0.0
homepage: https://github.com/truongsinh/dart-websocket

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  test_coverage: any
